### ISSUE TITLE
non proxy lambda integration

### ISSUE THREAD

**Issue by avinash317** [NickolasHKraus/cloudformation-templates#10]
hi 
i am using template to deploy lambda funtion 

AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.
Resources:

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Thumbnail
      StageName: test 
      EndpointConfiguration:
        Type: REGIONAL
      MethodSettings:
        - ResourcePath: /
          HttpMethod: POST
          MetricsEnabled: 'true'
          DataTraceEnabled: 'false'
        
  LambdaThumbnail:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: thumbnail
      Handler: com.amazonaws.lambda.thumbnail.Handler::handleRequest
      CodeUri: target/thumbnail-1.0.0.jar
      Runtime: java8
      MemorySize: 512
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /thumbnail
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
 

but it integrate lambda proxy in api gateway and throw error 502(internal server error) because response format didn't match
.......
i want to deploy non proxy lambda (custom lambda with custom response model) please help me if you can 
thank you......

**Comment by avinash317** [comment]
i also try you template also but i didn't figure out about code :. value in lambda function because i had deploy my funtion with cloudformation and this is java project and i had also use buildArti.. to deployment

**Comment by nickolashkraus** [comment]
Read [this](https://nickolaskraus.org/articles/creating-an-amazon-api-gateway-with-a-lambda-integration-using-cloudformation/) article. I go in-depth on setting up an API Gateway with a Lambda integration. The 502 you are getting is most likely due to a malformed response from the Lambda function.

*From the article given above...*

With a Lambda proxy integration, API Gateway requires the backend Lambda function to return output according to the following JSON format:

```json
{
  "isBase64Encoded": true|false,
  "statusCode": httpStatusCode,
  "headers": { "headerName": "headerValue", ... },
  "multiValueHeaders": { "headerName": ["headerValue", "headerValue2", ...], ... },
  "body": "..."
}
```

**Comment by avinash317** [comment]
Hi NickolasHKraus/cloudformation-templates but i don't want to integrated
lambda proxy

And i also don't to return response in this for...

Just I want to integrate custom lambda function and return custom response

When I deployed api through aws apigateway console it executed well but
when I deployed from sam template they integrate lambda proxy and throw
error 502(internal server error)
