### ISSUE TITLE
${Lambda.Arn} reference

### ISSUE THREAD

**Issue by ttangsv** [NickolasHKraus/cloudformation-templates#7]
https://github.com/NickolasHKraus/cloudformation-templates/blob/938842da32e630fde87e58e16019abbc7b0e9249/api-gateway-lambda-integration/template.yaml#L37

Hi there - thanks for sharing the template as I find it very helpful for my work however I found a minor issue here. `${Lambda.Arn}` doesn't work with `!Sub` on this line. I had to use the following code instead:

```
          Fn::Join:
            - ""
            - - !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/'
              - !GetAtt Lambda.Arn
              - '/invocations'
```

**Comment by nickolashkraus** [comment]
I use [`LambdaFunction`](https://github.com/NickolasHKraus/cloudformation-templates/blob/938842da32e630fde87e58e16019abbc7b0e9249/api-gateway-lambda-integration/template.yaml#L87), not `Lambda`.
