### ISSUE TITLE
A Question about Api Gateway Lambda integration.

### ISSUE THREAD

**Issue by nstfkc** [NickolasHKraus/cloudformation-templates#8]
Hello Nicholas, I want to say this before the question, I am so amazed by your blog especially CF related articles, thank you so much for this incredible work!.

Question: Based on this [template](https://github.com/NickolasHKraus/cloudformation-templates/blob/master/api-gateway-lambda-integration/template.yaml) what would be the best way to make api endpoint only accessible with api token. 

Also another thing made me confused;
In `AWS::ApiGateway::RestApi` resource there is `ApiKeySourceType` property set to `HEADER` but in `AWS::ApiGateway::Method` `ApiKeyRequired` property is set to `false`.  Is it common practice, in case there might be other methods can be protected via `api token`?

I am pretty new to CF, so sorry If am asking stupid questions.

Cheers!

**Comment by nickolashkraus** [comment]
Fröhliche Weihnachten aus Amerika!

> Question: Based on this [template](https://github.com/NickolasHKraus/cloudformation-templates/blob/master/api-gateway-lambda-integration/template.yaml) what would be the best way to make api endpoint only accessible with api token.

Check out the [Amazon API Gateway](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ApiGateway.html) documentation. It is certainly possible.

> In `AWS::ApiGateway::RestApi` resource there is `ApiKeySourceType` property set to `HEADER` but in `AWS::ApiGateway::Method` `ApiKeyRequired` property is set to `false`.  Is it common practice, in case there might be other methods can be protected via `api token`?

Short answer, yes.
