### ISSUE TITLE
Cloud formation api gateway HTTP integration

### ISSUE THREAD

**Issue by sanjeevkumarthakur** [NickolasHKraus/cloudformation-templates#9]
Hi, I'm trying to create a yaml template using Cloud formation to make an api gateway which integrate to HTTP but couldn't succeed as template throwing errors in yaml. Can you help me with the snippet.

Thanks in advance.
/Sanjeev

**Comment by nickolashkraus** [comment]
I am not sure what CloudFormation template you are referring to. Both `api-gateway-lambda-integration` and `api-gateway-mock-integration` are valid and deploy successfully.

**Comment by ben-burlingham** [comment]
I came across your excellent blog post (thank you) to try to fix an error...but unfortunately, when I run your template and test the endpoint, the same error appears:

> Execution failed due to configuration error: statusCode should be an integer which defined in request template

Seems like something's up.
